### ISSUE TITLE
More detailed installation instructions under 'Building'

### ISSUE THREAD

**Issue by dapsavoie** [civkit/civkit-node#10]
Now that nostr is installed as part of the setup locally as part of PR 9 (https://github.com/civkit/civkit-node/pull/9), I am proposing add the following 2 lines to the building section. Cargo should be lowercase and it might be helpful to specify the packages build into target.

```
cargo build
cd target/debug
#run commands above like ./civkitd
```

If the team agrees with such small changes to make this instruction correct and explicit, I am happy to do this.

**Comment by twshelton** [comment]
My thoughts are that any improvements to documentation would be welcome.  Go ahead and create a pull request and we can review further.

**Comment by nicosey** [comment]
please feel free to do pull request

**Comment by dapsavoie** [comment]
https://github.com/civkit/civkit-node/pull/11
ive added this here.

**Comment by nicosey** [comment]
PR merged
