### ISSUE TITLE
Add a toml config parser

### ISSUE THREAD

**Issue by ariard** [civkit/civkit-node#23]
`civkitd` will need a static config file on the host to discover its default settings and learn where is the nostr event database. We have already `clap` as a dependency so it can be used to build a parser of a TOML config file.

**Comment by ariard** [comment]
> Firstly, what would an example static config file look like? 

There is an example of bitcoind configuration file available here: https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/bitcoin.conf-annotated.txt

Relevant documentations can be:
- bitcoin core doc on configuration file https://github.com/bitcoin/bitcoin/blob/master/doc/bitcoin-conf.md
- toml documentation: https://toml.io/en/

Note bitcoin configuration file is not “pure” toml if i’m remembering correctly though approaching the syntax. In my opinion, the main advantage of using TOML over JSON is the ability to add comments (if you have custom settings and wanna remember why years after) and that it’s more straighforward to edit by hand (rather than JSON which is more verbose).

> Secondly, what filepath would it be in?

`/home/username/.civkitd/civkit.conf` if you’re on Linux, I think ? Old school UNIX standard.

If you have more questions, looking forward to answer them.

**Comment by dapsavoie** [comment]
I would imagine this toml config file would change overtime so the parser script would need to be updated. We could assume a toml like this

**Comment by ariard** [comment]
Yes the example given is a good one and if it can parse something of this complexity for the v0.1 of a toml config parser, I’ll take it.

For the name of the variables, matching `civkitd` (like `testnet=1` or `mainnet=1`, `noise_port`, `nostr_port`, `cli_port`and max number of subscriptions / relay clients) we can see during the code review.

**Comment by ariard** [comment]
Closed with #29.
