### ISSUE TITLE
Add a logging interface

### ISSUE THREAD

**Issue by ariard** [civkit/civkit-node#31]
Now we have TOML support to parse config file thanks #29 , the log could be captured in a `LoggerRecord` and be dropped in a file on-disk, rather being printed on stdout.

**Comment by dapsavoie** [comment]
@ariard I am taking a look at this. Ill submit a PR to start off and we can review from there.

**Comment by dapsavoie** [comment]
Please see new PR here https://github.com/civkit/civkit-node/pull/36

**Comment by dapsavoie** [comment]
@ariard  I believe we can close this.
