### ISSUE TITLE
Cargo build failed

### ISSUE THREAD

**Issue by vladimirfomene** [civkit/civkit-node#8]
I forked the code and tried building it using `cargo build`, but it fails. When looking at our `Cargo.toml` file I see we imported a `nostr` dependency which references a local path. Are there plans to ship a nostr crate with the project? Or can we use an existing dependency? If it is something I can fix, please let me know. I will like to contribute

**Comment by arno01** [comment]
Same here:

```
arno@x1:~/git/civkit-node$ cargo version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

arno@x1:~/git/civkit-node$ cargo build
    Updating crates.io index
    Updating git repository `https://github.com/civkit/rust-lightning.git`
error: failed to get `nostr` as a dependency of package `civkit v1.0.1 (/home/arno/git/civkit-node)`

Caused by:
  failed to load source for dependency `nostr`

Caused by:
  Unable to update /home/arno/git/nostr/crates/nostr

Caused by:
  failed to read `/home/arno/git/nostr/crates/nostr/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by nicosey** [comment]
Yes, done pull request just waiting for @ariard to approve
